"""📝 Writer — the LaTeX paper (built to PDF) and human-experiment protocols.

* The paper is rendered from ``templates/paper_template.tex``; figures are drawn
  by pgfplots straight from the simulation's data tables, so every number in the
  PDF comes from the archived run.
* Model-written prose is sanitised (:mod:`medusa.latex`) before it reaches TeX.
* Proposals for the Director are rendered from ``templates/human_proposal_template.md``.
"""

from __future__ import annotations

import datetime as dt
import re
import shutil
from pathlib import Path
from typing import Any

import jinja2

from ..latex import BuildResult, Sanitizer, TexSafe, build_pdf, escape_text, latex_env, mathify
from ..llm import LLMError, arr, obj, s
from ..models import (
    PAPER_SECTIONS,
    AnalysisReport,
    FigureSpec,
    MetaReview,
    PaperDraft,
    ProposalDoc,
    Review,
    RoutingDecision,
    ScoutReport,
    SimulationResult,
    Track,
)
from ..recipes import Recipe
from ..report import read_table
from ..state import AgentState
from ..utils import contains_cjk, slugify, write_json
from .base import Agent

SYSTEM = ("You are Writer, the scientific writer of Medusa Lab. You write clear, well-structured, honest research "
          "papers in the style of an arXiv preprint. Every quantitative claim must come from the provided "
          "simulation results; hedge appropriately and never invent data, citations or experiments.")

STYLE_RULES = (
    "Formatting rules: plain paragraphs separated by blank lines; you may use '- ' bullet lists; inline math as "
    "$...$; cite ONLY with \\citep{key} or \\citet{key} using the given keys; refer to figures as "
    "Figure~\\ref{fig:ID} and tables as Table~\\ref{tab:params} or Table~\\ref{tab:metrics}. Do not use any other "
    "LaTeX commands, do not write section headings, and do not use Markdown headings.")

PAPER_SCHEMA = obj({
    "title": s("concise paper title in English"),
    "abstract": s("150-220 words"),
    "keywords": arr(s()),
    **{name: s() for name in PAPER_SECTIONS},
    "figure_captions": arr(obj({"id": s(), "caption": s()})),
})
REVISION_SCHEMA = obj({**{name: s() for name in PAPER_SECTIONS}, "abstract": s(),
                       "response_to_reviewers": s("point-by-point response, one paragraph per request")})

SERIES_COLORS = ("c1", "c2", "c3")

PROPOSAL_LABELS = {
    "ja": {
        "doc": "実験提案書", "status": "ステータス", "status_value": "所長の承認待ち", "tldr": "TL;DR（30秒で読める要約）",
        "fun": "なぜ面白いのか（Fun Factor）", "background": "背景と先行研究", "hypothesis": "仮説",
        "why_human": "なぜ人間の手が必要なのか", "design": "実験デザイン", "design_type": "デザイン",
        "participants": "参加者", "power": "サンプルサイズ（検出力分析）", "conditions": "条件",
        "procedure": "手続き（プロトコル）", "measures": "測定項目", "analysis": "分析計画（事前登録用）",
        "link": "In-Silico研究との接続", "sim_findings": "今週のシミュレーション結果", "ethics": "倫理的配慮チェックリスト",
        "materials": "必要なもの", "schedule": "期間とコスト", "duration": "期間", "cost": "コスト目安",
        "risks": "リスクと対策", "next": "所長へのお願い（次のアクション）", "review": "Reviewer Agent の査読コメント",
        "theme": "テーマ", "cycle": "週次サイクル", "authors": "作成", "generated": "生成日時",
        "per_condition": "各条件", "units": "単位", "disclaimer": "本提案書は Medusa Lab のAIエージェントが自動生成した草案です。"
        "実施前に内容・倫理面を必ず人間が確認してください。",
        "design_types": {"between": "被験者間（条件ごとに別の参加者）", "within": "被験者内（全員が全条件）",
                         "observational": "観察研究", "survey": "調査研究"},
        "actions": ["実施するかどうかを判断する", "所属機関の倫理審査（IRB）の要否を確認する",
                    "予算と募集方法を決める", "事前登録（OSF等）の文面を確定する"],
        "no_review": "（査読待ち）", "strengths": "良い点", "weaknesses": "懸念点", "requests": "修正依頼",
        "literature": "関連文献",
    },
    "en": {
        "doc": "Experiment proposal", "status": "Status", "status_value": "awaiting the Director's approval",
        "tldr": "TL;DR", "fun": "Why this is fun", "background": "Background", "hypothesis": "Hypothesis",
        "why_human": "Why human hands are needed", "design": "Experimental design", "design_type": "Design",
        "participants": "Participants", "power": "Sample size (power analysis)", "conditions": "Conditions",
        "procedure": "Procedure (protocol)", "measures": "Measures", "analysis": "Analysis plan (pre-registration)",
        "link": "Link to the in-silico study", "sim_findings": "This week's simulation results",
        "ethics": "Ethics checklist", "materials": "Materials", "schedule": "Time and cost", "duration": "Duration",
        "cost": "Cost estimate", "risks": "Risks and mitigations", "next": "Next steps for the Director",
        "review": "Reviewer Agent comments", "theme": "Theme", "cycle": "Weekly cycle", "authors": "Prepared by",
        "generated": "Generated", "per_condition": "per condition", "units": "units",
        "disclaimer": "Draft generated by Medusa Lab's AI agents. A human must check content and ethics before running it.",
        "design_types": {"between": "between-subjects", "within": "within-subjects", "observational": "observational",
                         "survey": "survey"},
        "actions": ["Decide whether to run it", "Check whether ethics (IRB) review is required",
                    "Settle budget and recruitment", "Finalise the pre-registration text (e.g. OSF)"],
        "no_review": "(review pending)", "strengths": "Strengths", "weaknesses": "Concerns", "requests": "Requests",
        "literature": "Related literature",
    },
}


class WriterAgent(Agent):
    key = "writer"

    # ================================================================== paper
    def write_paper(self, scout: ScoutReport, analysis: AnalysisReport, routing: RoutingDecision,
                    sim: SimulationResult, recipe: Recipe) -> PaperDraft:
        self.status(AgentState.WRITING, self.msg("論文の草稿を執筆中", "Drafting the paper"), 0.1)
        draft: PaperDraft | None = None
        if not self.llm.offline:
            try:
                draft = self._llm_paper(scout, analysis, routing, sim)
            except LLMError as exc:
                self.note(f"LLM paper writing failed ({exc}); using the template writer.")
        if draft is None:
            draft = self._offline_paper(scout, analysis, routing, sim, recipe)
        return draft

    def revise_paper(self, draft: PaperDraft, meta: MetaReview, reviews: list[Review]) -> PaperDraft:
        self.status(AgentState.WRITING, self.msg(f"査読コメントに対応中（改訂{draft.revision + 1}）",
                                                 f"Revising (round {draft.revision + 1})"), 0.3)
        requests = [r for rev in reviews for r in rev.requests] + meta.required_changes
        new = PaperDraft.from_dict(draft.to_dict())
        new.revision = draft.revision + 1
        if not self.llm.offline:
            try:
                sections = "\n\n".join(f"### {k}\n{v}" for k, v in draft.sections.items())
                data = self.ask(system=SYSTEM, schema=REVISION_SCHEMA, prompt=(
                    f"Current draft (abstract and sections):\n### abstract\n{draft.abstract}\n\n{sections}\n\n"
                    f"Meta-review decision: {meta.decision}. Summary: {meta.summary}\nRequired changes:\n"
                    + "\n".join(f"- {r}" for r in requests) +
                    "\n\nRevise the sections to address every request that can be addressed with the existing "
                    "results (do not invent new data; acknowledge the rest as limitations). "
                    + STYLE_RULES))
                new.abstract = data.get("abstract") or draft.abstract
                for name in PAPER_SECTIONS:
                    if data.get(name):
                        new.sections[name] = data[name]
                new.response_to_reviewers = data.get("response_to_reviewers", "")
                return new
            except LLMError as exc:
                self.note(f"LLM revision failed ({exc}); adding a response letter only.")
        handled = []
        for req in requests:
            handled.append(f"- {req} Response: acknowledged; within this cycle the request is addressed by "
                           "stating it explicitly as a limitation and as future work.")
        new.sections["limitations"] = (draft.sections.get("limitations", "") + "\n\n"
                                       "Reviewer-raised issues that remain open:\n"
                                       + "\n".join(f"- {r}" for r in requests[:6]))
        new.response_to_reviewers = "\n".join(handled) or "No changes were requested."
        return new

    def render_and_build(self, draft: PaperDraft, scout: ScoutReport, analysis: AnalysisReport,
                         sim: SimulationResult, routing: RoutingDecision) -> PaperDraft:
        paper_dir = self.workdir("paper")
        data_src = self.ctx.cycle_dir / "coder" / "data"
        if data_src.is_dir():
            shutil.copytree(data_src, paper_dir / "data", dirs_exist_ok=True)
        tex_path = paper_dir / "paper.tex"
        self.status(AgentState.BUILDING, self.msg("LaTeXをPDFにビルド中", "Building the LaTeX PDF"), 0.6)
        result: BuildResult | None = None
        for level in ("full", "safe", "minimal"):
            tex = self._render_tex(draft, scout, analysis, sim, routing, level=level)
            tex_path.write_text(tex, encoding="utf-8")
            if not self.cfg.writer.compile_pdf:
                break
            result = build_pdf(tex_path, engine=self.cfg.writer.latex_engine)
            if result.ok or result.engine == "none":
                break
            self.note(f"LaTeX build ({level}) failed: {'; '.join(result.errors[:2])}")
        draft.tex_path = "paper/paper.tex"
        if result and result.ok:
            draft.pdf_path = "paper/paper.pdf"
            draft.build_ok = True
            draft.build_engine = result.engine
            draft.build_log = ""
            self.status(AgentState.DONE, self.msg(f"論文PDFを生成（{result.engine}, {result.seconds}秒）",
                                                  f"PDF built with {result.engine}"), 1.0)
        else:
            draft.build_ok = False
            draft.pdf_path = ""
            draft.build_engine = result.engine if result else "skipped"
            draft.build_log = "\n".join(result.errors) if result else "PDF compilation disabled"
            self.status(AgentState.DONE, self.msg("LaTeXソースを出力（PDFビルドなし）", "LaTeX source written (no PDF)"), 1.0)
        write_json(paper_dir / "draft.json", draft.to_dict())
        return draft

    # ------------------------------------------------------------------ LLM paper
    def _llm_paper(self, scout: ScoutReport, analysis: AnalysisReport, routing: RoutingDecision,
                   sim: SimulationResult) -> PaperDraft:
        refs = "\n".join(f"- {it.key}: {it.short_authors()} ({it.year}). {it.title}. {it.venue}"
                         for it in scout.literature)
        m = analysis.model
        hyps = "\n".join(f"- {h.id} [{h.track.value}] {h.statement}" for h in analysis.hypotheses)
        figs = "\n".join(f"- fig:{f.id}: y={f.y} vs x={f.x} from table {f.table}; draft caption: {f.caption}"
                         for f in sim.figures)
        metrics = "\n".join(f"- {k} = {v}" for k, v in sim.metrics.items())
        findings = "\n".join(f"- {f}" for f in sim.findings)
        tables = self._table_preview(sim)
        human = "\n".join(f"- {i.id}: {i.title_en or i.title}" for i in analysis.human_ideas
                          if i.hypothesis_id in routing.human)
        prompt = (
            f"Weekly theme chosen by the human Director: {self.theme.title}\n"
            f"Scout summary: {scout.summary}\nResearch gaps: " + "; ".join(p.statement for p in scout.problems) +
            f"\n\nReferences (use only these keys):\n{refs}\n\nModel: {m.name}\n{m.summary}\n"
            f"Equations (rendered separately as eq:1..): {'; '.join(m.equations)}\n"
            f"Assumptions: {'; '.join(m.assumptions)}\nHypotheses:\n{hyps}\n\n"
            f"Simulation ({sim.source}, seed {sim.seed}, runtime {sim.runtime_sec:.1f}s, isolation {sim.isolation}).\n"
            f"Summary: {sim.summary}\nMetrics:\n{metrics}\nFindings:\n{findings}\nFigures:\n{figs}\n"
            f"Data preview:\n{tables}\n\nHuman experiments proposed separately (mention in discussion/conclusion):\n"
            f"{human or '- none'}\n\nWrite the paper sections: {', '.join(PAPER_SECTIONS)}. The results section must "
            "discuss every figure and evaluate each in-silico hypothesis against the evidence (supported / partially / "
            "not supported). Limitations must be candid. " + STYLE_RULES)
        data = self.ask(system=SYSTEM, schema=PAPER_SCHEMA, prompt=prompt)
        return PaperDraft(
            title=data.get("title", ""), abstract=data.get("abstract", ""), keywords=list(data.get("keywords", []))[:8],
            sections={name: data.get(name, "") for name in PAPER_SECTIONS},
            figure_captions={c["id"].removeprefix("fig:"): c["caption"] for c in data.get("figure_captions", [])
                             if isinstance(c, dict) and c.get("id")},
            language=self.cfg.writer.paper_language)

    def _table_preview(self, sim: SimulationResult, rows: int = 8) -> str:
        """Header plus the first/last rows of each data table, so prose is grounded in actual numbers."""
        parts = []
        for name in sim.tables:
            path = self.ctx.cycle_dir / "coder" / "data" / f"{name}.dat"
            if not path.is_file():
                continue
            lines = path.read_text(encoding="utf-8").splitlines()
            body = lines[1:]
            shown = body if len(body) <= rows else body[: rows // 2] + ["..."] + body[-rows // 2:]
            parts.append(f"table {name} ({len(body)} rows):\n" + "\n".join([lines[0], *shown]))
        return "\n\n".join(parts)[:4000]

    # ------------------------------------------------------------------ offline paper
    def _offline_paper(self, scout: ScoutReport, analysis: AnalysisReport, routing: RoutingDecision,
                       sim: SimulationResult, recipe: Recipe) -> PaperDraft:
        theme = self.theme.title
        plan = analysis.plan
        sweep = next((p for p in analysis.model.parameters if p.name == plan.sweep_parameter), None)
        sweep_desc = f"{sweep.description} ${sweep.symbol}$" if sweep else plan.sweep_parameter
        values = ", ".join(f"{v:g}" for v in (plan.sweep_values or (sweep.sweep if sweep else []))) or "several values"
        findings = [mathify(f) for f in (sim.findings or [sim.summary])]
        retrieved = [it for it in scout.literature if not it.foundational]
        human = [i for i in analysis.human_ideas if i.hypothesis_id in routing.human]
        in_silico = [h for h in analysis.hypotheses if h.id in routing.in_silico]
        fig_refs = ", ".join(f"Figure~\\ref{{fig:{f.id}}}" for f in sim.figures)
        verdicts = []
        for h in in_silico:
            tpl = next((t for t in recipe.hypotheses if t.statement == h.statement), None)
            verdict, why = tpl.verdict(sim.metrics) if tpl else ("inconclusive", "no automatic criterion")
            verdicts.append((h, verdict, mathify(why)))
        n_supported = sum(1 for _, v, _ in verdicts if v == "supported")

        abstract = (
            f"Medusa Lab's weekly research theme, “{theme}”, was mapped onto the {recipe.title}. {recipe.summary} "
            f"We simulated the model while sweeping the {sweep_desc} over {values}, with {plan.replicates} independent "
            f"replicates per setting and 95\\% confidence intervals. {' '.join(findings[:2])} "
            f"Of the {len(verdicts)} in-silico hypotheses, {n_supported} {'is' if n_supported == 1 else 'are'} supported "
            f"by the simulation. {recipe.discussion[0]} The study was run end-to-end by autonomous agents in offline "
            "mode; its results are hypotheses for further work, and companion proposals describe experiments that need "
            "human participants.")
        intro = [
            f"This paper is the in-silico part of Medusa Lab's weekly research cycle. The Director chose the theme "
            f"“{theme}”; the Analyst agent translated it into a stylised, simulable mechanism, the "
            f"{recipe.title} ({recipe.field}).",
            recipe.background,
        ]
        if scout.problems:
            intro.append("The Scout agent identified the following open questions:\n" +
                         "\n".join(f"- {mathify(p.statement)}" for p in scout.problems[:3]))
        intro.append("Our contributions are:\n"
                     "- a reproducible simulation of the model with a systematic parameter sweep;\n"
                     f"- tests of {len(in_silico)} in-silico hypotheses;\n"
                     f"- {len(human)} human-experiment proposal(s) that confront the model with human behaviour.")
        related = [recipe.background]
        if retrieved:
            mentions = [f"\\citet{{{it.key}}} study {it.title.rstrip('.')}" for it in retrieved[:5]]
            related.append("Recent work retrieved by the Scout agent includes the following: "
                           + "; ".join(mentions) + ".")
        else:
            related.append("Literature retrieval was unavailable in this run, so the discussion relies on the "
                           "foundational references of the model.")
        model = [recipe.mechanism, "Assumptions:\n" + "\n".join(f"- {a}" for a in recipe.assumptions),
                 "The governing equations are given in Equations (1)--(" + str(len(analysis.model.equations)) +
                 ") and the parameters in Table~\\ref{tab:params}."]
        methods = [
            f"We swept the {sweep_desc} over {values}. For every setting we ran {plan.replicates} independent "
            f"replicates with seeds derived from the base seed {sim.seed}, and report means with 95\\% t-intervals.",
            f"The simulation ({sim.script}) was executed in Medusa Lab's sandbox (isolation: {sim.isolation or 'basic'}); "
            f"the full run took {sim.runtime_sec:.1f} seconds. The code, parameters and raw data tables are archived "
            "with this paper, so every number and figure can be regenerated.",
        ]
        results = [f"{fig_refs} summarise the parameter sweep." if sim.figures else "",
                   "\n".join(f"- {f}" for f in findings),
                   "Table~\\ref{tab:metrics} lists the summary metrics."]
        for h, verdict, why in verdicts:
            results.append(f"\\textbf{{{h.id}}} is {verdict}: {why}.")
        discussion = ["\n".join(f"- {d}" for d in recipe.discussion)]
        if human:
            discussion.append("Several questions cannot be settled in silico. We therefore propose human experiments: "
                              + "; ".join(f"{i.id} “{i.title_en or i.title}”" for i in human) +
                              ". Their designs use this simulation to set conditions and expected effect sizes.")
        limitations = ["\n".join(f"- {x}" for x in recipe.limitations),
                       "The paper was written by Medusa Lab's template writer (offline mode, no language model); "
                       "the mapping from the theme to the model is a deliberate simplification, and hypothesis "
                       "verdicts follow pre-specified numerical criteria."]
        headline = recipe.headline.get("en", "")
        conclusion = [f"Within the {recipe.title}, " + (findings[0][0].lower() + findings[0][1:] if findings else "")
                      + (f" In short: {headline}." if headline else "")
                      + " The companion human-experiment proposals outline how to test the mechanism with people."]
        sections = {
            "introduction": "\n\n".join(intro), "related_work": "\n\n".join(related),
            "model": "\n\n".join(model), "methods": "\n\n".join(methods),
            "results": "\n\n".join(r for r in results if r), "discussion": "\n\n".join(discussion),
            "limitations": "\n\n".join(limitations), "conclusion": "\n\n".join(conclusion),
        }
        return PaperDraft(title=f"{recipe.title}: an in-silico study", abstract=abstract,
                          keywords=[recipe.field.split("/")[0].strip(), *[k for k in self.theme.keywords if k.isascii()][:3],
                                    "agent-based simulation"],
                          sections=sections, language="en")

    # ------------------------------------------------------------------ LaTeX rendering
    def _render_tex(self, draft: PaperDraft, scout: ScoutReport, analysis: AnalysisReport, sim: SimulationResult,
                    routing: RoutingDecision, *, level: str) -> str:
        unicode_doc = draft.language == "ja" or any(
            contains_cjk(x) for x in [draft.title, draft.abstract, self.theme.title, *draft.sections.values()])
        if level != "full":
            unicode_doc = False  # fall back to plain pdflatex-safe output
        keys = {it.key for it in scout.literature}
        labels = {f"fig:{f.id}" for f in sim.figures} | {"tab:params", "tab:metrics"} | {
            f"eq:{i}" for i in range(1, len(analysis.model.equations) + 1)}
        san = Sanitizer(cite_keys=keys, labels=labels, unicode_ok=unicode_doc)

        def prose(text: str) -> TexSafe:
            if level == "full":
                return san.paragraph_text(text)
            plain = re.sub(r"\\cite[pt]?\{[^}]*\}", "", text)
            return TexSafe("\n\n".join(escape_text(p, unicode_ok=False) for p in plain.split("\n\n")))

        def inline(text: str) -> TexSafe:
            return san.inline(text) if level == "full" else TexSafe(escape_text(text, unicode_ok=False))

        equations = []
        if level != "minimal":
            for eq in analysis.model.equations:
                safe = san.math(eq)
                if safe is not None:
                    equations.append(safe)
        params = []
        for p in analysis.model.parameters:
            sym = san.math(p.symbol) if level == "full" else None
            params.append({"symbol": sym or TexSafe(escape_text(p.name)), "name": p.name,
                           "description": p.description, "default": f"{p.default:g}",
                           "sweep": ", ".join(f"{v:g}" for v in p.sweep) or "--"})
        figures = [] if level == "minimal" else [self._figure_ctx(f, draft, san, level) for f in sim.figures]
        figures = [f for f in figures if f]
        metrics = [{"name": TexSafe(escape_text(k).replace(r"\_", r"\_\allowbreak{}")), "value": _fmt_value(v),
                    "description": inline(mathify(sim.metric_notes.get(k, "")))} for k, v in sim.metrics.items()]
        references = [self._reference_ctx(it) for it in scout.literature]
        human = [i for i in analysis.human_ideas if i.hypothesis_id in routing.human]
        env = latex_env(self.cfg.templates_dir, unicode_ok=unicode_doc)
        template = env.get_template("paper_template.tex")
        model_line = ("Language model: " + self.llm.model) if not self.llm.offline else "Offline template mode (no language model)"
        ctx: dict[str, Any] = {
            "unicode": unicode_doc,
            "title": inline(draft.title),
            "theme": inline(self.theme.title) if unicode_doc or not contains_cjk(self.theme.title) else TexSafe(
                escape_text(", ".join(k for k in self.theme.keywords if k.isascii()) or "see the weekly report")),
            "abstract": prose(draft.abstract),
            "keywords": draft.keywords,
            "lab_name": self.cfg.lab.name,
            "director": self.cfg.lab.director if unicode_doc or not contains_cjk(self.cfg.lab.director) else "the Director",
            "cycle_id": self.theme.cycle_id,
            "date": dt.date.today().isoformat(),
            "model_line": model_line,
            "sections": {name: prose(draft.sections.get(name, "")) for name in PAPER_SECTIONS},
            "equations": equations,
            "parameters": params,
            "figures": figures,
            "metrics": metrics,
            "hypotheses": [{"id": h.id, "statement": inline(h.statement), "track": h.track.value}
                           for h in analysis.hypotheses if h.track == Track.IN_SILICO],
            "proposals": [{"id": i.id, "title": i.title_en or i.title if unicode_doc else (i.title_en or i.id),
                           "n": i.sample_size} for i in human],
            "references": references,
            "response": prose(draft.response_to_reviewers) if draft.response_to_reviewers else None,
            "revision": draft.revision,
            "sim": {"seed": sim.seed, "runtime": f"{sim.runtime_sec:.1f}", "isolation": sim.isolation or "basic",
                    "source": sim.source},
        }
        if san.dropped:
            self.log.info("sanitizer dropped: %s", san.dropped[:10])
        return template.render(**ctx)

    def _figure_ctx(self, fig: FigureSpec, draft: PaperDraft, san: Sanitizer, level: str) -> dict[str, Any] | None:
        if not re.match(r"^[A-Za-z][A-Za-z0-9_\-]*$", fig.id) or not re.match(r"^[A-Za-z][A-Za-z0-9_\-]*$", fig.table):
            return None
        data_file = self.ctx.cycle_dir / "paper" / "data" / f"{fig.table}.dat"
        if not data_file.is_file():
            return None
        header = data_file.read_text(encoding="utf-8").splitlines()[0].split()
        if not all(re.match(r"^[A-Za-z][A-Za-z0-9_]*$", col) for col in header):
            return None
        if fig.x not in header or not all(y in header for y in fig.y):
            return None
        _, rows = read_table(data_file)
        index = {name: i for i, name in enumerate(header)}

        def positive(col: str | None) -> bool:
            return bool(col) and all(len(r) > index[col] and r[index[col]] > 0 for r in rows)  # type: ignore[index]

        series = []
        for i, y in enumerate(fig.y[:3]):
            lower = fig.lower[i] if i < len(fig.lower) and fig.lower[i] in header else None
            upper = fig.upper[i] if i < len(fig.upper) and fig.upper[i] in header else None
            band = bool(lower and upper) and (not fig.logy or (positive(lower) and positive(upper)))
            series.append({"y": y, "label": fig.labels[i] if i < len(fig.labels) else y,
                           "lower": lower if band else None, "upper": upper if band else None,
                           "color": SERIES_COLORS[i], "n": i, "marks": len(rows) <= 30})
        caption = draft.figure_captions.get(fig.id) or fig.caption or fig.title
        text = san.inline if level == "full" else (lambda t: TexSafe(escape_text(t)))
        # column names/paths were validated by medusa_sim ([A-Za-z][A-Za-z0-9_]*), so they are passed verbatim
        for item in series:
            for k in ("y", "lower", "upper"):
                if item[k]:
                    item[k] = TexSafe(item[k])
        return {"id": fig.id, "label": TexSafe(f"fig:{fig.id}"), "table": TexSafe(f"data/{fig.table}.dat"),
                "x": TexSafe(fig.x), "series": series, "xlabel": text(fig.xlabel or fig.x),
                "ylabel": text(fig.ylabel or ", ".join(fig.y)), "caption": text(caption), "logx": fig.logx,
                "logy": fig.logy, "legend": len(series) > 1}

    @staticmethod
    def _reference_ctx(it) -> dict[str, Any]:  # type: ignore[no-untyped-def]
        label = f"{it.short_authors()}({it.year or 'n.d.'})"
        url = it.url if re.match(r"^https?://[A-Za-z0-9._~:/?#\[\]@!$&'()*+,;=%-]+$", it.url or "") else ""
        return {"key": it.key, "label": label, "authors": ", ".join(it.authors[:6]) + (" et al." if len(it.authors) > 6 else ""),
                "year": it.year or "n.d.", "title": it.title, "venue": it.venue,
                "url": TexSafe(url.replace("%", r"\%").replace("#", r"\#")) if url else None}

    # ================================================================== proposals
    def write_proposals(self, analysis: AnalysisReport, routing: RoutingDecision, sim: SimulationResult | None,
                        scout: ScoutReport, reviews: dict[str, Review] | None = None) -> list[ProposalDoc]:
        ideas = [i for i in analysis.human_ideas if i.hypothesis_id in routing.human or not i.hypothesis_id]
        if not ideas:
            return []
        self.status(AgentState.WRITING, self.msg(f"人間向け実験提案書を{len(ideas)}件作成中",
                                                 f"Writing {len(ideas)} human-experiment proposal(s)"), 0.5)
        out = self.workdir("proposals")
        env = jinja2.Environment(loader=jinja2.FileSystemLoader(str(self.cfg.templates_dir)),
                                 autoescape=False, trim_blocks=True, lstrip_blocks=True,
                                 undefined=jinja2.StrictUndefined, keep_trailing_newline=True)
        env.filters["cell"] = lambda v: str(v).replace("|", "\\|").replace("\n", " ")
        template = env.get_template("human_proposal_template.md")
        lang = self.ctx.lang
        docs = []
        for idea in ideas:
            name = f"{idea.id}-{slugify(idea.title_en or idea.title, 40)}.md"
            text = template.render(
                t=PROPOSAL_LABELS[lang], idea=idea, lang=lang, theme=self.theme, lab=self.cfg.lab,
                cycle_id=self.theme.cycle_id, generated=dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
                findings=(sim.findings if sim and sim.ok else []), design_label=PROPOSAL_LABELS[lang]["design_types"].get(
                    idea.design_type, idea.design_type),
                literature=[it for it in scout.literature][:5], review=(reviews or {}).get(idea.id),
                paper_available=bool(sim and sim.ok))
            (out / name).write_text(text, encoding="utf-8")
            docs.append(ProposalDoc(idea_id=idea.id, title=idea.title, path=f"proposals/{name}",
                                    sample_size=idea.sample_size))
        index = [f"# {PROPOSAL_LABELS[lang]['doc']} — {self.theme.cycle_id}", "",
                 f"**{PROPOSAL_LABELS[lang]['theme']}:** {self.theme.title}", ""]
        index += [f"- [{d.idea_id}: {d.title}]({Path(d.path).name}) — n = {d.sample_size} "
                  f"{PROPOSAL_LABELS[lang]['per_condition']}" for d in docs]
        (out / "README.md").write_text("\n".join(index) + "\n", encoding="utf-8")
        return docs


def _fmt_value(value: Any) -> str:
    if isinstance(value, float):
        return f"{value:.4g}"
    if value is None:
        return "--"
    return str(value)
